### ISSUE TITLE
Document Gateway configuration and construction

### ISSUE THREAD

**Issue by ryanneve** [sunny-day-flooding-project/tutorials#3]

**Comment by ththelen** [comment]
I would suggest that Tony and Ryan review and add to the gateway and sensor construction/configuration documents that Lauren and I are developing in the Wiki tab. We could use this thread to notify each other when documentation is ready for Tony/Ryan's review.

**Comment by ththelen** [comment]
I have first drafts of the **Communications Box** and **Raspberry Pi OS & Settings** manuals ready to go in the Wiki tab.
